services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    # This section is for system-level packages
    packages:
      - libraqm0
